name: fetch origin
on:
  push:
  schedule:
    - cron: 0 */48 * * *   # 每隔48小时
jobs:
  fetch:
    name: fetch origin
    runs-on: ubuntu-latest
    steps:
      - uses: TobKed/github-forks-sync-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }} # 令牌
           upstream_repository: Rongronggg9/RSS-to-Telegram-Bot  # 上游仓库
           target_repository: ${{ secrets.GITHUB_REPOSITORY }}  # 你要推送的仓库
           upstream_branch: master  # 默认是拉取上游仓库的 master 分支
           target_branch: master  # 默认推送到你的仓库 master 分支
           force: false  # 是否强制推送
           tags: true  # 确定是否使用 - tags
